site_name: ToyML
repo_url: https://github.com/ai-glimpse/toyml
repo_name: ai-glimpse/toyml
edit_uri: ""
site_description: Machine Learning from Scratch
site_author: Xiangzhuang Shen
copyright: Copyright &copy; 2017 Xiangzhuang Shen

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Quick Start: quickstart.md
      - User Guide:
          - Read First: user-guide/1-read-first.md
  - Algorithms:
      - Clustering:
          - Kmeans: algorithms/clustering/kmeans.md
          - DBSCAN: algorithms/clustering/dbscan.md
          - DIANA: algorithms/clustering/diana.md
          - AGNES: algorithms/clustering/agnes.md
      - Classification:
          - KNN: algorithms/classification/knn.md
      - EVT:
          - SPOT: algorithms/evt/spot.md


  - Changelog: CHANGELOG.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

docs_dir: docs

extra_css:
  - css/extra.css

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shenxiangzhuang/ToyML
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xiangzhuang-shen-a81825157/

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - abbr
  - admonition
  - attr_list
  - footnotes

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
      cite_inline: false
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          - https://python-markdown.github.io/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            show_docstring_classes: true
            show_docstring_attributes: true
            heading_level: 2
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: false
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
#            show_symbol_type_toc: true
            signature_crossrefs: true
            show_root_members_full_path: true
            show_root_toc_entry: false
